DROP TABLE IF EXISTS user1;
DROP TABLE IF EXISTS post;

CREATE TABLE user1 (
    id INTEGER PRIMARY KEY NOT NULL,
    username TEXT UNIQUE NOT NULL,
    passwords TEXT NOT NULL
);

CREATE TABLE post (
    id INTEGER PRIMARY KEY NOT NULL,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user1 (id)
);